In [2]:
import numpy as np
import matplotlib.pyplot as plt

In [3]:

from google.colab import files
uploaded=files.upload()

Saving data set .csv to data set .csv


In [4]:
arr = np.genfromtxt('data set .csv',delimiter=',',skip_header=1)

In [5]:
arr

array([[9.50e+02, 2.00e+00, 1.00e+00, 1.80e+01, 2.80e+06],
       [1.10e+03, 2.00e+00, 2.00e+00, 1.50e+01, 3.40e+06],
       [1.30e+03, 3.00e+00, 2.00e+00, 1.20e+01, 4.20e+06],
       [1.50e+03, 3.00e+00, 2.00e+00, 1.00e+01, 5.10e+06],
       [1.70e+03, 3.00e+00, 3.00e+00, 8.00e+00, 6.20e+06],
       [1.40e+03, 3.00e+00, 2.00e+00, 1.40e+01, 4.70e+06],
       [2.10e+03, 4.00e+00, 3.00e+00, 5.00e+00, 8.30e+06],
       [1.90e+03, 4.00e+00, 3.00e+00, 6.00e+00, 7.20e+06],
       [1.00e+03, 2.00e+00, 1.00e+00, 2.00e+01, 3.00e+06],
       [2.30e+03, 4.00e+00, 4.00e+00, 3.00e+00, 9.10e+06],
       [1.60e+03, 3.00e+00, 2.00e+00, 9.00e+00, 5.60e+06],
       [2.50e+03, 5.00e+00, 4.00e+00, 2.00e+00, 9.80e+06],
       [1.20e+03, 2.00e+00, 2.00e+00, 1.60e+01, 3.60e+06],
       [1.80e+03, 4.00e+00, 3.00e+00, 7.00e+00, 6.80e+06],
       [2.60e+03, 5.00e+00, 4.00e+00, 2.00e+00, 1.02e+07],
       [1.45e+03, 3.00e+00, 2.00e+00, 1.30e+01, 4.90e+06],
       [2.00e+03, 4.00e+00, 3.00e+00, 4.00e+00, 7.80e+06

In [6]:
arr.shape

(50, 5)

In [7]:
arr=np.round(arr).astype(int)
arr

array([[     950,        2,        1,       18,  2800000],
       [    1100,        2,        2,       15,  3400000],
       [    1300,        3,        2,       12,  4200000],
       [    1500,        3,        2,       10,  5100000],
       [    1700,        3,        3,        8,  6200000],
       [    1400,        3,        2,       14,  4700000],
       [    2100,        4,        3,        5,  8300000],
       [    1900,        4,        3,        6,  7200000],
       [    1000,        2,        1,       20,  3000000],
       [    2300,        4,        4,        3,  9100000],
       [    1600,        3,        2,        9,  5600000],
       [    2500,        5,        4,        2,  9800000],
       [    1200,        2,        2,       16,  3600000],
       [    1800,        4,        3,        7,  6800000],
       [    2600,        5,        4,        2, 10200000],
       [    1450,        3,        2,       13,  4900000],
       [    2000,        4,        3,        4,  7800000

In [8]:
area = arr[:,0]
area

array([ 950, 1100, 1300, 1500, 1700, 1400, 2100, 1900, 1000, 2300, 1600,
       2500, 1200, 1800, 2600, 1450, 2000, 1550, 2750,  900, 2400, 1750,
       3000, 1350, 2200, 1650, 2800, 1250, 1850, 2050, 1500, 2900,  950,
       1700, 2150, 1950, 1450, 2550, 1100, 2350, 1600, 2700, 1800, 1050,
       3100, 1550, 2250, 1750, 3200, 2000])

In [9]:
bedrooms=arr[:,1]
bedrooms

array([2, 2, 3, 3, 3, 3, 4, 4, 2, 4, 3, 5, 2, 4, 5, 3, 4, 3, 5, 2, 4, 3,
       6, 3, 4, 3, 5, 2, 4, 4, 3, 6, 2, 3, 4, 4, 3, 5, 2, 4, 3, 5, 4, 2,
       6, 3, 4, 3, 6, 4])

In [10]:
bathrooms=arr[:,2]
bathrooms

array([1, 2, 2, 2, 3, 2, 3, 3, 1, 4, 2, 4, 2, 3, 4, 2, 3, 2, 5, 1, 4, 3,
       5, 2, 4, 3, 5, 2, 3, 3, 2, 5, 1, 3, 3, 3, 2, 4, 2, 4, 2, 5, 3, 1,
       5, 2, 4, 3, 6, 3])

In [11]:
age=arr[:,3]
age

array([18, 15, 12, 10,  8, 14,  5,  6, 20,  3,  9,  2, 16,  7,  2, 13,  4,
       11,  1, 22,  3,  8,  1, 15,  4,  9,  1, 17,  6,  5, 10,  1, 19,  8,
        4,  5, 12,  2, 18,  3, 10,  1,  7, 20,  1, 11,  3,  8,  1,  5])

In [12]:
price=arr[:,4]
price

array([ 2800000,  3400000,  4200000,  5100000,  6200000,  4700000,
        8300000,  7200000,  3000000,  9100000,  5600000,  9800000,
        3600000,  6800000, 10200000,  4900000,  7800000,  5300000,
       10800000,  2600000,  9400000,  6500000, 11800000,  4500000,
        8600000,  5900000, 11000000,  3900000,  7100000,  8100000,
        5000000, 11500000,  2900000,  6100000,  8400000,  7600000,
        4800000, 10000000,  3300000,  9200000,  5400000, 10600000,
        6900000,  3100000, 12100000,  5200000,  8900000,  6400000,
       12400000,  7900000])

In [13]:
average_price=sum(price)/len(price)
f'average_price: ₹{average_price:,.2f}'

'average_price: ₹6,918,000.00'

In [14]:
height_price=np.max(price)
f'height_price :₹ {height_price}'


'height_price :₹ 12400000'

In [15]:
lowest_price=np.min(price)
f'lowest_price :₹ {lowest_price}'

'lowest_price :₹ 2600000'

In [16]:
average_area=np.sum(area)/len(area)
f'average_area :{average_area} sq'

'average_area :1870.0 sq'

In [17]:
arr[bedrooms>4]


array([[    2500,        5,        4,        2,  9800000],
       [    2600,        5,        4,        2, 10200000],
       [    2750,        5,        5,        1, 10800000],
       [    3000,        6,        5,        1, 11800000],
       [    2800,        5,        5,        1, 11000000],
       [    2900,        6,        5,        1, 11500000],
       [    2550,        5,        4,        2, 10000000],
       [    2700,        5,        5,        1, 10600000],
       [    3100,        6,        5,        1, 12100000],
       [    3200,        6,        6,        1, 12400000]])

In [18]:
arr[price>6000000]

array([[    1700,        3,        3,        8,  6200000],
       [    2100,        4,        3,        5,  8300000],
       [    1900,        4,        3,        6,  7200000],
       [    2300,        4,        4,        3,  9100000],
       [    2500,        5,        4,        2,  9800000],
       [    1800,        4,        3,        7,  6800000],
       [    2600,        5,        4,        2, 10200000],
       [    2000,        4,        3,        4,  7800000],
       [    2750,        5,        5,        1, 10800000],
       [    2400,        4,        4,        3,  9400000],
       [    1750,        3,        3,        8,  6500000],
       [    3000,        6,        5,        1, 11800000],
       [    2200,        4,        4,        4,  8600000],
       [    2800,        5,        5,        1, 11000000],
       [    1850,        4,        3,        6,  7100000],
       [    2050,        4,        3,        5,  8100000],
       [    2900,        6,        5,        1, 11500000

In [19]:
a=np.argmax(price)
arr[a]

array([    3200,        6,        6,        1, 12400000])

In [20]:
arr[np.argmin(price)]

array([    900,       2,       1,      22, 2600000])

In [21]:
average_age=np.mean(age)
f'average_age : {average_age}'

'average_age : 8.32'

In [22]:
total_price=np.sum(price)
f'total_price:{total_price}'

'total_price:345900000'

In [23]:
price_per_sqft = price / area

print(price_per_sqft)

[2947.36842105 3090.90909091 3230.76923077 3400.         3647.05882353
 3357.14285714 3952.38095238 3789.47368421 3000.         3956.52173913
 3500.         3920.         3000.         3777.77777778 3923.07692308
 3379.31034483 3900.         3419.35483871 3927.27272727 2888.88888889
 3916.66666667 3714.28571429 3933.33333333 3333.33333333 3909.09090909
 3575.75757576 3928.57142857 3120.         3837.83783784 3951.2195122
 3333.33333333 3965.51724138 3052.63157895 3588.23529412 3906.97674419
 3897.43589744 3310.34482759 3921.56862745 3000.         3914.89361702
 3375.         3925.92592593 3833.33333333 2952.38095238 3903.22580645
 3354.83870968 3955.55555556 3657.14285714 3875.         3950.        ]


In [24]:
np.sort(price)[::-1]



array([12400000, 12100000, 11800000, 11500000, 11000000, 10800000,
       10600000, 10200000, 10000000,  9800000,  9400000,  9200000,
        9100000,  8900000,  8600000,  8400000,  8300000,  8100000,
        7900000,  7800000,  7600000,  7200000,  7100000,  6900000,
        6800000,  6500000,  6400000,  6200000,  6100000,  5900000,
        5600000,  5400000,  5300000,  5200000,  5100000,  5000000,
        4900000,  4800000,  4700000,  4500000,  4200000,  3900000,
        3600000,  3400000,  3300000,  3100000,  3000000,  2900000,
        2800000,  2600000])

In [25]:

house_numbers=np.arange(0,len(price+1))
house_numbers


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [ ]:
## line graph

plt.figure(figsize=(10,8))
plt.plot(house_numbers,price,marker='s',markersize=6,mfc='red',color="blue",mec='red')
plt.title("House Prices",fontsize=16, fontweight="bold")
plt.xlabel("House Number")
plt.ylabel("Price (₹)")
plt.grid(axis='y')
ax = plt.gca()
ax.set_facecolor('lightyellow')
ax.spines['top'].set_linewidth(3)
ax.spines['bottom'].set_linewidth(3)
ax.spines['left'].set_linewidth(3)
ax.spines['right'].set_linewidth(3)
plt.ticklabel_format(style='plain', axis='y')
plt.savefig("line_chart.png", dpi=300, bbox_inches="tight")
plt.show()
from google.colab import files
files.download("line_chart.png")

In [ ]:
## bar graph

plt.figure(figsize=(10,8))
plt.bar(house_numbers,
        area,
        color="skyblue",
        edgecolor="black",
        linewidth=1.5,label='house area')
plt.title("House Area Comparison", fontsize=16, fontweight="bold")
plt.xlabel("House Number")
plt.ylabel("Area (sq.ft)")
plt.legend(loc="upper left")
ax = plt.gca()
ax.set_facecolor("lightyellow")
for spine in ax.spines.values():
    spine.set_linewidth(2)
plt.savefig("bar_chart.png", dpi=300)

plt.show()

files.download("bar_chart.png")

In [ ]:
## scatter

plt.figure(figsize=(10,8))
plt.scatter(
    area,price ,color='red' ,marker='*'
)
plt.title("Area vs Price", fontsize=16, fontweight="bold")
plt.xlabel("Area (sq.ft)")
plt.ylabel("Price (₹)")
ax=plt.gca()
ax.set_facecolor('lightyellow')
ax.spines['top'].set_linewidth(2)
ax.spines['bottom'].set_linewidth(2)
ax.spines['left'].set_linewidth(2)
ax.spines['right'].set_linewidth(2)
plt.grid(axis='y')
plt.ticklabel_format(style='plain',axis='y')
plt.savefig("scatter_plot.png", dpi=300)
plt.show()
from google.colab import files
files.download("scatter_plot.png")

In [ ]:
## histogram

plt.figure(figsize=(10,8))
plt.hist(price,bins=8,color="green",
         edgecolor="black")
plt.title("price distrubution ",fontsize=16,fontweight='bold')
plt.xlabel('price(₹)')
plt.ylabel("Number of Houses")
plt.ticklabel_format(style="plain",axis="x")
plt.savefig("histogram_plot.png",dpi=300)
plt.show()
files.download("histogram_plot.png")

In [30]:
bedrooms


array([2, 2, 3, 3, 3, 3, 4, 4, 2, 4, 3, 5, 2, 4, 5, 3, 4, 3, 5, 2, 4, 3,
       6, 3, 4, 3, 5, 2, 4, 4, 3, 6, 2, 3, 4, 4, 3, 5, 2, 4, 3, 5, 4, 2,
       6, 3, 4, 3, 6, 4])

In [31]:
unique, counts = np.unique(bedrooms, return_counts=True)

In [32]:
counts

array([ 9, 16, 15,  6,  4])

In [33]:
total=sum(unique)
total

np.int64(20)

In [34]:
for i in counts:
  print(f'{(i/50)*100} %')

18.0 %
32.0 %
30.0 %
12.0 %
8.0 %


In [49]:
labels=[f'{int(i)}BHK'for i in unique]
labels

['2BHK', '3BHK', '4BHK', '5BHK', '6BHK']

In [ ]:
# pie chart
plt.pie(
    counts,
    labels=labels,
    autopct='%1.1f%%'
)
plt.title("Bedroom Distribution")
startangle=90,
shadow=True,
plt.savefig("pie_chat.png",dpi=300)
plt.show()
files.download("pie_chat.png")